
services:
  share-backend:
    build: ./share-backend/.
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - ./share-backend/server/database/share.sqlite3:~/db

  share-frontend:
    build: ./share-frontend/.
    ports:
      - "3000:3000"
